name: Clang-Format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: |
          for i in 12 13 14 15; do which gcc-$i || true; done
          for i in 12 13 14 15; do which gcc-$i --version || true; done
